# Generated by Django 3.2.2 on 2021-06-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_article_biography_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authors.article')),
            ],
        ),
    ]
